python predict_pfp_lr-interpro.py --c run-all_goa-BP-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-MF-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-CC-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-BP-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-MF-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-CC-PCA.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-BP-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-MF-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-CC-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-bp-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-bp-pca-1000.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-bp-pca.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-bp.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-cc-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-cc-pca.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-cc.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-mf-8800.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-mf-pca.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_cafa3-mf.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-BP.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-MF.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-FULL-CC.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-MF.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-BP.PFP.ini
python predict_pfp_lr-interpro.py --c run-all_goa-CC.PFP.ini
